etlp_fc_snn_dvsgesture_t1:
  name: etlp_fc_snn_dvsgesture_t1
  opt: false
  trainer:
    name: etlp
    supported_net_types:
    - fc
    - rec
    lr: 4.207053950287933e-05
    surrogate_scale: 0.15227525095137953
    weight_l1: 0.0
    weight_l2: 0.0
    update_rate_hz: 1000.0
    dt_ms: 1.0
    feedback_distribution: normal
    feedback_scale: 1.745734676972377
    use_optimizer: false
    grad_clip: 0.0
  model:
    name: fc_snn
    net_type: fc
    in_shape:
    - 32768
    hidden_sizes:
    - 2048
    num_classes: 11
    beta: 0.9142118522312097
    threshold: 1.2080725777960455
    reset_mechanism: subtract
    out_integrator: false
    algorithm_name: etlp
  dataset:
    name: dvsgesture
    supported_net_types:
    - fc
    - rec
    - conv
    - vgg9
    T: 20
    pin_memory: false
    num_workers: 4
    data_root: null
    download: true
    use_cache: true
  runtime:
    epochs: 20
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
    batch_size: 64
    progress: false
  optuna: {}
