name: eprop_r_snn_shd_t3
opt: false
trainer:
  name: eprop
  supported_net_types:
  - rec
  lr: 5.415244119402538e-05
  gamma: 0.2216968971838151
  dt: null
  tau_mem: null
  tau_out: null
  threshold: null
  lr_layer_norm:
  - 1.0
  - 1.0
  - 1.0
  use_optimizer: true
  update_last: false
  update_every: 1
  seq_batch_size: 1
model:
  name: r_snn
  net_type: rec
  in_shape:
  - 700
  hidden_sizes:
  - 256
  num_classes: 20
  beta: 0.8997037220101252
  threshold: 0.9319450186421158
  reset_mechanism: subtract
  out_integrator: true
  algorithm_name: eprop
dataset:
  name: shd
  supported_net_types:
  - fc
  - rec
  T: 100
  seed: 292
  pin_memory: true
  num_workers: 4
  data_root: null
  download: true
  use_cache: true
runtime:
  epochs: 20
  device: cuda
  seed: 42
  log_level: INFO
  neurobench: false
  batch_size: 256
  progress: true
optuna: {}
