esd_rtrl_r_snn_dvsgesture_t12:
  name: esd_rtrl_r_snn_dvsgesture_t12
  opt: false
  trainer:
    name: esd_rtrl
    supported_net_types:
    - fc
    - rec
    - conv
    lr: 0.0003153489956509138
    use_optimizer: true
    etrace_decay: 0.8801020019314798
    gamma: 0.640612171203472
    lr_layer_norm:
    - 1.0
    - 1.0
    - 1.0
    detach_state_each_step: true
    debug_unused_learning_signals: false
  model:
    name: r_snn
    net_type: rec
    in_shape:
    - 32768
    hidden_sizes:
    - 1024
    num_classes: 11
    beta: 0.8064108218289199
    threshold: 0.5164359516219927
    reset_mechanism: subtract
    out_integrator: false
    algorithm_name: esd_rtrl
  dataset:
    name: dvsgesture
    supported_net_types:
    - fc
    - rec
    - conv
    - vgg9
    T: 20
    pin_memory: false
    num_workers: 4
    data_root: null
    download: true
    use_cache: true
  runtime:
    epochs: 20
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
    batch_size: 32
    progress: false
  optuna: {}
