decolle_conv_snn_dvscifar10_t2:
  name: decolle_conv_snn_dvscifar10_t2
  opt: false
  trainer:
    name: decolle
    supported_net_types:
    - fc
    - conv
    lr: 0.021368329072358756
    g_scale: 0.5034443102887247
    burn_in: 0
    surrogate: sigmoid
    surrogate_scale: 4.4546743769349115
    delta: 0.2650640588680905
    h_with_noise: false
    omega_std: 0.5
    lambda_u_upper: 0.0
    lambda_u_lower: 0.0
    lr_scale_per_layer: false
  model:
    name: conv_snn
    net_type: conv
    in_shape:
    - 2
    - 128
    - 128
    num_classes: 10
    beta: 0.8578060261623122
    threshold: 1.024756431632238
    out_integrator: true
    algorithm_name: decolle
  dataset:
    name: dvscifar10
    supported_net_types:
    - fc
    - rec
    - conv
    - vgg9
    T: 10
    pin_memory: false
    num_workers: 4
    train_fraction: 0.9
    data_root: null
    download: true
    use_cache: true
  runtime:
    epochs: 20
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
    batch_size: 64
    progress: true
  optuna: {}
