eprop_r_snn_dvscifar10_t7:
  name: eprop_r_snn_dvscifar10_t7
  opt: false
  trainer:
    name: eprop
    supported_net_types:
    - rec
    lr: 0.00234238498471129
    gamma: 0.1185801650879991
    dt: null
    tau_mem: null
    tau_out: null
    threshold: null
    lr_layer_norm:
    - 1.0
    - 1.0
    - 1.0
    use_optimizer: true
    update_last: false
    update_every: 1
    seq_batch_size: 1
  model:
    name: r_snn
    net_type: rec
    in_shape:
    - 32768
    hidden_sizes:
    - 256
    num_classes: 10
    beta: 0.9154335218612732
    threshold: 0.6705241236872915
    reset_mechanism: subtract
    out_integrator: true
    algorithm_name: eprop
  dataset:
    name: dvscifar10
    supported_net_types:
    - fc
    - rec
    - conv
    - vgg9
    T: 10
    pin_memory: false
    num_workers: 4
    train_fraction: 0.9
    data_root: null
    download: true
    use_cache: true
  runtime:
    epochs: 20
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
    batch_size: 32
    progress: true
  optuna: {}
