name: etlp_r_snn_mnist_t0
opt: false
trainer:
  name: etlp
  supported_net_types:
  - fc
  - rec
  lr: 0.00031489116479568613
  surrogate_scale: 0.9556428757689246
  weight_l1: 0.0
  weight_l2: 0.0
  update_rate_hz: 1000.0
  dt_ms: 1.0
  feedback_distribution: normal
  feedback_scale: 1.4907884894416696
  use_optimizer: false
  grad_clip: 0.0
model:
  name: r_snn
  net_type: rec
  in_shape:
  - 784
  hidden_sizes:
  - 256
  num_classes: 10
  beta: 0.9137451119974369
  threshold: 0.6560186404424365
  reset_mechanism: subtract
  out_integrator: false
  algorithm_name: etlp
dataset:
  name: mnist
  supported_net_types:
  - fc
  - rec
  - conv
  T: 10
  seed: 156
  pin_memory: false
  download: true
  data_root: null
  num_workers: 4
  direct_coding: false
runtime:
  epochs: 20
  device: cuda
  seed: 42
  log_level: INFO
  neurobench: false
  batch_size: 256
  progress: true
optuna: {}
