name: bptt_r_snn_fashionmnist_t3
opt: false
trainer:
  name: bptt
  supported_net_types:
  - fc
  - rec
  - conv
  lr: 0.021368329072358756
  loss_type: ce_rate
  grad_clip: null
  use_optimizer: true
model:
  name: r_snn
  net_type: rec
  in_shape:
  - 784
  hidden_sizes:
  - 256
  num_classes: 10
  beta: 0.8403444310288725
  threshold: 0.6818249672071006
  reset_mechanism: subtract
  out_integrator: false
  algorithm_name: bptt
dataset:
  name: fashionmnist
  supported_net_types:
  - fc
  - rec
  - conv
  T: 10
  seed: 184
  pin_memory: false
  download: true
  data_root: null
  num_workers: 4
  direct_coding: false
runtime:
  epochs: 20
  device: cuda
  seed: 42
  log_level: INFO
  neurobench: false
  batch_size: 256
  progress: true
optuna: {}
