name: tp_conv_snn_svhn_t8
opt: false
trainer:
  name: tp
  supported_net_types:
  - fc
  - rec
  - conv
  - vgg9
  lr: 2.1248638632431267e-05
  alpha: 0.23422389067399646
  beta: 0.5221613715661636
  vth: 0.6903963969159173
  surrogate_scale: 1.0
  train_target_propagator: true
  use_optimizer: true
model:
  name: conv_snn
  net_type: conv
  in_shape:
  - 3
  - 32
  - 32
  num_classes: 10
  beta: 0.8738486850410017
  threshold: 0.7713490317738959
  out_integrator: true
  algorithm_name: tp
dataset:
  name: svhn
  supported_net_types:
  - fc
  - rec
  - conv
  - vgg9
  T: 10
  seed: 829
  direct_coding: true
  pin_memory: false
  download: true
  data_root: null
  num_workers: 4
runtime:
  epochs: 20
  device: cuda
  seed: 42
  log_level: INFO
  neurobench: false
  batch_size: 256
  progress: true
optuna: {}
