bptt_otttnet_svhn:
  name: bptt_otttnet_svhn
  opt: false
  trainer:
    name: bptt
    supported_net_types:
    - fc
    - rec
    - conv
    lr: 4.207988669606632e-05
    loss_type: ce_rate
    grad_clip: null
    use_optimizer: true
  model:
    name: vgg9
    net_type: vgg9
    in_channels: 3
    num_classes: 10
    input_shape:
    - 3
    - 32
    - 32
    head_type: global_linear
    use_tp_pool: false
    channels:
    - 64
    - 128
    - 256
    - 256
    - 512
    - 512
    - 512
    - 512
    beta: 0.4076362190319798
    threshold: 0.5580836121681995
    conv_gain: 1.0
    scale_after_lif:
        value: 2.74
        type: float
        min: 1.5
        max: 3.5
    surrogate_kind: sigmoid
    surrogate_slope: 4.0
    pool_after_blocks:
    - 2
    - 4
    algorithm_name: bptt
  dataset:
    name: svhn
    supported_net_types:
    - fc
    - rec
    - conv
    - vgg9
    T: 10
    seed: 867
    direct_coding: true
    pin_memory: false
    download: true
    data_root: null
    num_workers: 4
  runtime:
    epochs: 200
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: true
    batch_size: 128
    progress: false
  optuna: {}
