name: ostl_r_snn_fashionmnist_t4
opt: false
trainer:
  name: ostl
  supported_net_types:
  - fc
  - rec
  lr: 0.00016480446427978953
  grad_clip: 0.0
  use_optimizer: false
  deferred: false
  feedback_alignment: false
  ostl_complete: false
model:
  name: r_snn
  net_type: rec
  in_shape:
  - 784
  hidden_sizes:
  - 256
  num_classes: 10
  beta: 0.8997037220101252
  threshold: 0.9319450186421158
  reset_mechanism: subtract
  out_integrator: false
  algorithm_name: ostl
dataset:
  name: fashionmnist
  supported_net_types:
  - fc
  - rec
  - conv
  T: 10
  seed: 292
  pin_memory: false
  download: true
  data_root: null
  num_workers: 4
  direct_coding: false
runtime:
  epochs: 20
  device: cuda
  seed: 42
  log_level: INFO
  neurobench: false
  batch_size: 256
  progress: true
optuna: {}
