name: tp_fc_snn_fashionmnist_t3
opt: false
trainer:
  name: tp
  supported_net_types:
  - fc
  - rec
  - conv
  - vgg9
  lr: 3.280829084730047e-05
  alpha: 0.324615969623105
  beta: 0.6795173032139089
  vth: 0.8472839810604431
  surrogate_scale: 1.0
  train_target_propagator: true
  use_optimizer: true
model:
  name: fc_snn
  net_type: fc
  in_shape:
  - 784
  hidden_sizes:
  - 800
  num_classes: 10
  beta: 0.9491834326646726
  threshold: 0.6996737821583597
  reset_mechanism: subtract
  out_integrator: true
  algorithm_name: tp
dataset:
  name: fashionmnist
  supported_net_types:
  - fc
  - rec
  - conv
  T: 10
  seed: 515
  pin_memory: false
  download: true
  data_root: null
  num_workers: 4
  direct_coding: false
runtime:
  epochs: 20
  device: cuda
  seed: 42
  log_level: INFO
  neurobench: false
  batch_size: 256
  progress: true
optuna: {}
