name: bptt_conv_snn_nmnist_t9
opt: false
trainer:
  name: bptt
  supported_net_types:
  - fc
  - rec
  - conv
  lr: 0.00016536937182824412
  loss_type: ce_rate
  grad_clip: null
  use_optimizer: true
model:
  name: conv_snn
  net_type: conv
  in_shape:
  - 2
  - 34
  - 34
  num_classes: 10
  beta: 0.818557701661213
  threshold: 1.1842330265121568
  algorithm_name: bptt
dataset:
  name: nmnist
  supported_net_types:
  - fc
  - rec
  - conv
  T: 10
  seed: 441
  pin_memory: false
  num_workers: 4
  data_root: null
  download: true
  use_cache: true
runtime:
  epochs: 20
  device: cuda
  seed: 42
  log_level: INFO
  neurobench: false
  batch_size: 256
  progress: true
optuna: {}
