name: tp_conv_snn_cifar10_t2
opt: false
trainer:
  name: tp
  supported_net_types:
  - fc
  - rec
  - conv
  - vgg9
  lr: 4.7050592819076514e-05
  alpha: 0.2224002392622278
  beta: 0.6490786990501735
  vth: 0.9297077179586855
  surrogate_scale: 1.0
  train_target_propagator: true
  use_optimizer: true
model:
  name: conv_snn
  net_type: conv
  in_shape:
  - 3
  - 32
  - 32
  num_classes: 10
  beta: 0.882069553542002
  threshold: 0.7912291401980419
  out_integrator: true
  algorithm_name: tp
dataset:
  name: cifar10
  supported_net_types:
  - fc
  - rec
  - conv
  - vgg9
  T: 6
  seed: 612
  direct_coding: true
  pin_memory: false
  download: true
  data_root: null
  num_workers: 4
runtime:
  epochs: 20
  device: cuda
  seed: 42
  log_level: INFO
  neurobench: false
  batch_size: 256
  progress: true
optuna: {}
