esd_rtrl_conv_snn_cifar10_t0:
  name: esd_rtrl_conv_snn_cifar10_t0
  opt: false
  trainer:
    name: esd_rtrl
    supported_net_types:
    - fc
    - rec
    - conv
    lr: 0.0054557357298011385
    use_optimizer: true
    etrace_decay: 0.904491621162969
    gamma: 0.19621371083766237
    lr_layer_norm:
    - 1.0
    - 1.0
    - 1.0
    detach_state_each_step: true
    debug_unused_learning_signals: false
  model:
    name: conv_snn
    net_type: conv
    in_shape:
    - 3
    - 32
    - 32
    num_classes: 10
    beta: 0.8803425703718091
    threshold: 0.8902900193806906
    out_integrator: true
    algorithm_name: esd_rtrl
  dataset:
    name: cifar10
    supported_net_types:
    - fc
    - rec
    - conv
    - vgg9
    T: 6
    direct_coding: true
    pin_memory: false
    download: true
    data_root: null
    num_workers: 4
  runtime:
    epochs: 20
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
    batch_size: 128
    progress: false
  optuna: {}
