name: stsf_fc_snn_cifar10_t4
opt: false
trainer:
  name: stsf
  supported_net_types:
  - fc
  lr: 0.00016480446427978953
  use_optimizer: false
model:
  name: fc_snn
  net_type: fc
  in_shape:
  - 3072
  hidden_sizes:
  - 1024
  - 512
  num_classes: 10
  beta: 0.8997037220101252
  threshold: 0.9319450186421158
  reset_mechanism: subtract
  out_integrator: false
  algorithm_name: stsf
dataset:
  name: cifar10
  supported_net_types:
  - fc
  - rec
  - conv
  - vgg9
  T: 6
  seed: 292
  direct_coding: true
  pin_memory: false
  download: true
  data_root: null
  num_workers: 4
runtime:
  epochs: 20
  device: cuda
  seed: 42
  log_level: INFO
  neurobench: false
  batch_size: 256
  progress: true
optuna: {}
