ottt_fc_snn_mnist_t8:
  name: ottt_fc_snn_mnist_t8
  opt: false
  trainer:
    name: ottt
    supported_net_types:
    - fc
    - rec
    - conv
    - vgg9
    lr: 0.0001740299082352256
    online_updates: true
    loss_lambda: 0.3235185145617433
    grad_clip: 0.0
    sanitize_grads: false
  model:
    name: fc_snn
    net_type: fc
    in_shape:
    - 784
    hidden_sizes:
    - 256
    num_classes: 10
    beta: 0.9834700862841663
    threshold: 1.3083973481164612
    reset_mechanism: subtract
    out_integrator: false
    algorithm_name: ottt
  dataset:
    name: mnist
    supported_net_types:
    - fc
    - rec
    - conv
    T: 10
    pin_memory: false
    download: true
    data_root: null
    num_workers: 4
    direct_coding: false
  runtime:
    epochs: 20
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
    batch_size: 256
    progress: true
  optuna: {}
