name: tp_r_snn_fashionmnist_t8
opt: false
trainer:
  name: tp
  supported_net_types:
  - fc
  - rec
  - conv
  - vgg9
  lr: 2.1248638632431267e-05
  alpha: 0.23422389067399646
  beta: 0.5221613715661636
  vth: 0.6903963969159173
  surrogate_scale: 1.0
  train_target_propagator: true
  use_optimizer: true
model:
  name: r_snn
  net_type: rec
  in_shape:
  - 784
  hidden_sizes:
  - 256
  num_classes: 10
  beta: 0.8738486850410017
  threshold: 0.7713490317738959
  reset_mechanism: subtract
  out_integrator: true
  algorithm_name: tp
dataset:
  name: fashionmnist
  supported_net_types:
  - fc
  - rec
  - conv
  T: 10
  seed: 829
  pin_memory: false
  download: true
  data_root: null
  num_workers: 4
  direct_coding: false
runtime:
  epochs: 20
  device: cuda
  seed: 42
  log_level: INFO
  neurobench: false
  batch_size: 256
  progress: true
optuna: {}
