name: ostl_fc_snn_shd_t5
opt: false
trainer:
  name: ostl
  supported_net_types:
  - fc
  - rec
  lr: 0.0028016351587162596
  grad_clip: 0.0
  use_optimizer: false
  deferred: false
  feedback_alignment: false
  ostl_complete: false
model:
  name: fc_snn
  net_type: fc
  in_shape:
  - 700
  hidden_sizes:
  - 512
  num_classes: 20
  beta: 0.826503833523888
  threshold: 0.7921446485352182
  reset_mechanism: subtract
  out_integrator: false
  algorithm_name: ostl
dataset:
  name: shd
  supported_net_types:
  - fc
  - rec
  T: 100
  seed: 367
  pin_memory: true
  num_workers: 4
  data_root: null
  download: true
  use_cache: true
runtime:
  epochs: 20
  device: cuda
  seed: 42
  log_level: INFO
  neurobench: false
  batch_size: 256
  progress: true
optuna: {}
