name: tp_conv_snn_mnist_t5
opt: false
trainer:
  name: tp
  supported_net_types:
  - fc
  - rec
  - conv
  - vgg9
  lr: 0.009777718780862659
  alpha: 0.3363369430229684
  beta: 0.5478593358631281
  vth: 1.1210796318145881
  surrogate_scale: 1.0
  train_target_propagator: true
  use_optimizer: true
model:
  name: conv_snn
  net_type: conv
  in_shape:
  - 1
  - 28
  - 28
  num_classes: 10
  beta: 0.8836289738105243
  threshold: 0.6220382348447788
  out_integrator: true
  algorithm_name: tp
dataset:
  name: mnist
  supported_net_types:
  - fc
  - rec
  - conv
  T: 10
  seed: 496
  pin_memory: false
  download: true
  data_root: null
  num_workers: 4
  direct_coding: false
runtime:
  epochs: 20
  device: cuda
  seed: 42
  log_level: INFO
  neurobench: false
  batch_size: 256
  progress: true
optuna: {}
