name: esd_rtrl_r_snn_dvscifar10_t5
opt: false
trainer:
  name: esd_rtrl
  supported_net_types:
  - fc
  - rec
  - conv
  lr: 0.0026926469100861782
  use_optimizer: true
  etrace_decay: 0.5835568206067728
  gamma: 0.15204127438822362
  lr_layer_norm:
  - 1.0
  - 1.0
  - 1.0
  detach_state_each_step: true
  debug_unused_learning_signals: false
model:
  name: r_snn
  net_type: rec
  in_shape:
  - 32768
  hidden_sizes:
  - 512
  num_classes: 10
  beta: 0.9802882520781333
  threshold: 1.4656320330745594
  reset_mechanism: subtract
  out_integrator: true
  algorithm_name: esd_rtrl
dataset:
  name: dvscifar10
  supported_net_types:
  - fc
  - rec
  - conv
  - vgg9
  T: 10
  seed: 809
  pin_memory: false
  num_workers: 4
  train_fraction: 0.9
  data_root: null
  download: true
  use_cache: true
runtime:
  epochs: 20
  device: cuda
  seed: 42
  log_level: INFO
  neurobench: false
  batch_size: 256
  progress: true
optuna: {}
