name: tp_r_snn_cifar10_t9
opt: false
trainer:
  name: tp
  supported_net_types:
  - fc
  - rec
  - conv
  - vgg9
  lr: 0.00020874681332882274
  alpha: 0.31407843910613786
  beta: 0.7659210807475417
  vth: 0.46910906996971513
  surrogate_scale: 1.0
  train_target_propagator: true
  use_optimizer: true
model:
  name: r_snn
  net_type: rec
  in_shape:
  - 3072
  hidden_sizes:
  - 512
  - 256
  num_classes: 10
  beta: 0.9524174263432675
  threshold: 0.5745506436797708
  reset_mechanism: subtract
  out_integrator: true
  algorithm_name: tp
dataset:
  name: cifar10
  supported_net_types:
  - fc
  - rec
  - conv
  - vgg9
  T: 6
  seed: 987
  direct_coding: true
  pin_memory: false
  download: true
  data_root: null
  num_workers: 4
runtime:
  epochs: 20
  device: cuda
  seed: 42
  log_level: INFO
  neurobench: false
  batch_size: 256
  progress: true
optuna: {}
