name: bptt_r_snn_cifar10_t7
opt: false
trainer:
  name: bptt
  supported_net_types:
  - fc
  - rec
  - conv
  lr: 0.00234238498471129
  loss_type: ce_rate
  grad_clip: null
  use_optimizer: true
model:
  name: r_snn
  net_type: rec
  in_shape:
  - 3072
  hidden_sizes:
  - 512
  - 256
  num_classes: 10
  beta: 0.8088255784167996
  threshold: 1.1075448519014384
  reset_mechanism: subtract
  out_integrator: false
  algorithm_name: bptt
dataset:
  name: cifar10
  supported_net_types:
  - fc
  - rec
  - conv
  - vgg9
  T: 6
  seed: 171
  direct_coding: true
  pin_memory: false
  download: true
  data_root: null
  num_workers: 4
runtime:
  epochs: 20
  device: cuda
  seed: 42
  log_level: INFO
  neurobench: false
  batch_size: 256
  progress: true
optuna: {}
