ottt_conv_snn_fashionmnist_t1:
  name: ottt_conv_snn_fashionmnist_t1
  opt: false
  trainer:
    name: ottt
    supported_net_types:
    - fc
    - rec
    - conv
    - vgg9
    lr: 0.0003776663327107339
    online_updates: true
    loss_lambda: 0.00037758875456826864
    grad_clip: 0.0
    sanitize_grads: false
  model:
    name: conv_snn
    net_type: conv
    in_shape:
    - 1
    - 28
    - 28
    num_classes: 10
    beta: 0.8110358863119579
    threshold: 1.366176145774935
    algorithm_name: ottt
  dataset:
    name: fashionmnist
    supported_net_types:
    - fc
    - rec
    - conv
    T: 10
    pin_memory: false
    download: true
    data_root: null
    num_workers: 4
    direct_coding: false
  runtime:
    epochs: 20
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
    batch_size: 256
    progress: true
  optuna: {}
