esd_rtrl_conv_snn_cifar10_t2:
  name: esd_rtrl_conv_snn_cifar10_t2
  opt: false
  trainer:
    name: esd_rtrl
    supported_net_types:
    - fc
    - rec
    - conv
    lr: 0.000273391559904501
    use_optimizer: true
    etrace_decay: 0.980401477683805
    gamma: 0.33057394418904346
    lr_layer_norm:
    - 1.0
    - 1.0
    - 1.0
    detach_state_each_step: true
    debug_unused_learning_signals: false
  model:
    name: conv_snn
    net_type: conv
    in_shape:
    - 3
    - 32
    - 32
    num_classes: 10
    beta: 0.9539243305737862
    threshold: 1.2347499711896202
    out_integrator: true
    algorithm_name: esd_rtrl
  dataset:
    name: cifar10
    supported_net_types:
    - fc
    - rec
    - conv
    - vgg9
    T: 6
    direct_coding: true
    pin_memory: false
    download: true
    data_root: null
    num_workers: 4
  runtime:
    epochs: 20
    device: cuda
    seed: 44
    log_level: INFO
    neurobench: false
    batch_size: 128
    progress: false
  optuna: {}
