name: tp_conv_snn_nmnist_t9
opt: false
trainer:
  name: tp
  supported_net_types:
  - fc
  - rec
  - conv
  - vgg9
  lr: 0.00020874681332882274
  alpha: 0.31407843910613786
  beta: 0.7659210807475417
  vth: 0.46910906996971513
  surrogate_scale: 1.0
  train_target_propagator: true
  use_optimizer: true
model:
  name: conv_snn
  net_type: conv
  in_shape:
  - 2
  - 34
  - 34
  num_classes: 10
  beta: 0.9524174263432675
  threshold: 0.5745506436797708
  out_integrator: true
  algorithm_name: tp
dataset:
  name: nmnist
  supported_net_types:
  - fc
  - rec
  - conv
  T: 10
  seed: 987
  pin_memory: false
  num_workers: 4
  data_root: null
  download: true
  use_cache: true
runtime:
  epochs: 20
  device: cuda
  seed: 42
  log_level: INFO
  neurobench: false
  batch_size: 256
  progress: true
optuna: {}
