tp_vgg9_cifar10:
  name: tp_vgg9_cifar10
  opt: true
  optuna:
    n_trials: 50
  trainer:
    name: tp
    lr:
      value: 1e-4
      type: float
      min: 1e-5
      max: 1e-2
      log: true
  model:
    name: vgg9
  dataset:
    name: cifar10
    batch_size: 64
    T: 10
  runtime:
    epochs: 5
    seed: 42
    device: cuda
