tp_vgg9_svhn:
  name: tp_vgg9_svhn
  opt: true
  optuna:
    n_trials: 200
  trainer:
    name: tp
    lr:
      value: 1e-4
      type: float
      min: 1e-5
      max: 1e-2
      log: true
  model:
    name: vgg9
  dataset:
    name: svhn
    T: 10
  runtime:
    epochs: 5
    batch_size: 32
    seed: 42
    device: cuda
