name: tp_fc_snn_dvscifar10_t7
opt: false
trainer:
  name: tp
  supported_net_types:
  - fc
  - rec
  - conv
  - vgg9
  lr: 4.8280425192712865e-05
  alpha: 0.961409550098685
  beta: 0.8798150834469461
  vth: 1.427398729877027
  surrogate_scale: 1.0
  train_target_propagator: true
  use_optimizer: true
model:
  name: fc_snn
  net_type: fc
  in_shape:
  - 32768
  hidden_sizes:
  - 1024
  - 512
  num_classes: 10
  beta: 0.9700171965812533
  threshold: 1.097899978811085
  reset_mechanism: subtract
  out_integrator: true
  algorithm_name: tp
dataset:
  name: dvscifar10
  supported_net_types:
  - fc
  - rec
  - conv
  - vgg9
  T: 10
  seed: 922
  pin_memory: false
  num_workers: 4
  train_fraction: 0.9
  data_root: null
  download: true
  use_cache: true
runtime:
  epochs: 20
  device: cuda
  seed: 42
  log_level: INFO
  neurobench: false
  batch_size: 256
  progress: true
optuna: {}
