trainers:
- ell
models:
- fc_snn
- r_snn
- conv_snn
datasets:
- DVSCifar10
runtime:
  epochs: 20
  device: cuda
  seed: 42
  neurobench: false
opt: true
optuna:
  n_trials: 100
  direction: maximize
  sampler: tpe
  pruner: null
  timeout: null
  storage: null
