trainers:
- stsf
models:
- fc_snn
- r_snn
- conv_snn
datasets:
- FashionMNIST
runtime:
  epochs: 5
  device: cuda
  seed: 42
  neurobench: false
opt: true
optuna:
  n_trials: 50
  direction: maximize
  sampler: tpe
  pruner: null
  timeout: null
  storage: null
