trainers:
- tp
models:
- vgg9_tp
datasets:
- SVHN
runtime:
  epochs: 10
  device: cuda
  seed: 42
  neurobench: false
opt: true
optuna:
  n_trials: 50
  direction: maximize
  sampler: tpe
  pruner: null
  timeout: null
  storage: null
