name: ostl_r_snn_nmnist_t6
opt: false
trainer:
  name: ostl
  supported_net_types:
  - fc
  - rec
  lr: 0.0006672367170464204
  grad_clip: 0.0
  use_optimizer: false
  deferred: false
  feedback_alignment: false
  ostl_complete: false
model:
  name: r_snn
  net_type: rec
  in_shape:
  - 2312
  hidden_sizes:
  - 256
  num_classes: 10
  beta: 0.9491834326646726
  threshold: 0.6996737821583597
  reset_mechanism: subtract
  out_integrator: false
  algorithm_name: ostl
dataset:
  name: nmnist
  supported_net_types:
  - fc
  - rec
  - conv
  T: 10
  seed: 515
  pin_memory: false
  num_workers: 4
  data_root: null
  download: true
  use_cache: true
runtime:
  epochs: 20
  device: cuda
  seed: 42
  log_level: INFO
  neurobench: false
  batch_size: 256
  progress: true
optuna: {}
