name: tp_r_snn_nmnist_t4
opt: false
trainer:
  name: tp
  supported_net_types:
  - fc
  - rec
  - conv
  - vgg9
  lr: 0.001553544580758846
  alpha: 0.09366338795679786
  beta: 0.7976969774317049
  vth: 0.5046289484247498
  surrogate_scale: 1.0
  train_target_propagator: true
  use_optimizer: true
model:
  name: r_snn
  net_type: rec
  in_shape:
  - 2312
  hidden_sizes:
  - 256
  num_classes: 10
  beta: 0.8123598026672032
  threshold: 1.4488855372533331
  reset_mechanism: subtract
  out_integrator: true
  algorithm_name: tp
dataset:
  name: nmnist
  supported_net_types:
  - fc
  - rec
  - conv
  T: 10
  seed: 966
  pin_memory: false
  num_workers: 4
  data_root: null
  download: true
  use_cache: true
runtime:
  epochs: 20
  device: cuda
  seed: 42
  log_level: INFO
  neurobench: false
  batch_size: 256
  progress: true
optuna: {}
