osttp_fc_snn_mnist_t1:
  name: osttp_fc_snn_mnist_t1
  opt: false
  trainer:
    name: osttp
    supported_net_types:
    - fc
    - rec
    lr: 4.207988669606632e-05
    pseudo: tanh
    output_loss: mse
    feedback_scale: 0.39638958863878504
    feedback_seed: 42
    grad_clip: 0.0
    use_optimizer: true
  model:
    name: fc_snn
    net_type: fc
    in_shape:
    - 784
    hidden_sizes:
    - 256
    num_classes: 10
    beta: 0.8110358863119579
    threshold: 1.366176145774935
    reset_mechanism: subtract
    out_integrator: false
    algorithm_name: osttp
  dataset:
    name: mnist
    supported_net_types:
    - fc
    - rec
    - conv
    T: 10
    pin_memory: false
    download: true
    data_root: null
    num_workers: 4
    direct_coding: false
  runtime:
    epochs: 20
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
    batch_size: 256
    progress: true
  optuna: {}
