name: etlp_fc_snn_svhn_t1
opt: false
trainer:
  name: etlp
  supported_net_types:
  - fc
  - rec
  lr: 1.7073967431528103e-05
  surrogate_scale: 0.8795585311974417
  weight_l1: 0.0
  weight_l2: 0.0
  update_rate_hz: 1000.0
  dt_ms: 1.0
  feedback_distribution: normal
  feedback_scale: 1.2421185223120967
  use_optimizer: false
  grad_clip: 0.0
model:
  name: fc_snn
  net_type: fc
  in_shape:
  - 3072
  hidden_sizes:
  - 1024
  - 512
  num_classes: 10
  beta: 0.9345337897812487
  threshold: 0.5205844942958024
  reset_mechanism: subtract
  out_integrator: false
  algorithm_name: etlp
dataset:
  name: svhn
  supported_net_types:
  - fc
  - rec
  - conv
  - vgg9
  T: 10
  seed: 970
  direct_coding: true
  pin_memory: false
  download: true
  data_root: null
  num_workers: 4
runtime:
  epochs: 20
  device: cuda
  seed: 42
  log_level: INFO
  neurobench: false
  batch_size: 256
  progress: true
optuna: {}
