name: tp_conv_snn_mnist_t6
opt: false
trainer:
  name: tp
  supported_net_types:
  - fc
  - rec
  - conv
  - vgg9
  lr: 1.3403002793227001e-05
  alpha: 0.9047611779540551
  beta: 0.6268021909840082
  vth: 1.0950267412247783
  surrogate_scale: 1.0
  train_target_propagator: true
  use_optimizer: true
model:
  name: conv_snn
  net_type: conv
  in_shape:
  - 1
  - 28
  - 28
  num_classes: 10
  beta: 0.8592251044569881
  threshold: 1.0200680211778108
  out_integrator: true
  algorithm_name: tp
dataset:
  name: mnist
  supported_net_types:
  - fc
  - rec
  - conv
  T: 10
  seed: 547
  pin_memory: false
  download: true
  data_root: null
  num_workers: 4
  direct_coding: false
runtime:
  epochs: 20
  device: cuda
  seed: 42
  log_level: INFO
  neurobench: false
  batch_size: 256
  progress: true
optuna: {}
