ottt_conv_snn_dvsgesture_t9:
  name: ottt_conv_snn_dvsgesture_t9
  opt: false
  trainer:
    name: ottt
    supported_net_types:
    - fc
    - rec
    - conv
    - vgg9
    lr: 0.0013389279116695488
    online_updates: true
    loss_lambda: 0.0002297662414082499
    grad_clip: 0.0
    sanitize_grads: false
  model:
    name: conv_snn
    net_type: conv
    in_shape:
    - 2
    - 128
    - 128
    num_classes: 11
    beta: 0.9300042750373099
    threshold: 0.9401524937396013
    algorithm_name: ottt
  dataset:
    name: dvsgesture
    supported_net_types:
    - fc
    - rec
    - conv
    - vgg9
    T: 20
    pin_memory: false
    num_workers: 4
    data_root: null
    download: true
    use_cache: true
  runtime:
    epochs: 20
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
    batch_size: 256
    progress: true
  optuna: {}
