osttp_r_snn_cifar10_t8:
  name: osttp_r_snn_cifar10_t8
  opt: false
  trainer:
    name: osttp
    supported_net_types:
    - fc
    - rec
    lr: 1.8205657658407255e-05
    pseudo: tanh
    output_loss: mse
    feedback_scale: 1.9028825207813331
    feedback_seed: 42
    grad_clip: 0.0
    use_optimizer: true
  model:
    name: r_snn
    net_type: rec
    in_shape:
    - 3072
    hidden_sizes:
    - 512
    - 256
    num_classes: 10
    beta: 0.9834700862841663
    threshold: 1.3083973481164612
    reset_mechanism: subtract
    out_integrator: false
    algorithm_name: osttp
  dataset:
    name: cifar10
    supported_net_types:
    - fc
    - rec
    - conv
    - vgg9
    T: 6
    direct_coding: true
    pin_memory: false
    download: true
    data_root: null
    num_workers: 4
  runtime:
    epochs: 20
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
    batch_size: 256
    progress: true
  optuna: {}
