ottt_r_snn_cifar10_t6:
  name: ottt_r_snn_cifar10_t6
  opt: false
  trainer:
    name: ottt
    supported_net_types:
    - fc
    - rec
    - conv
    - vgg9
    lr: 0.004863951003835903
    online_updates: true
    loss_lambda: 0.08023102291340051
    grad_clip: 0.0
    sanitize_grads: false
  model:
    name: r_snn
    net_type: rec
    in_shape:
    - 3072
    hidden_sizes:
    - 512
    - 256
    num_classes: 10
    beta: 0.8379380186100884
    threshold: 1.0142344384136117
    reset_mechanism: subtract
    out_integrator: false
    algorithm_name: ottt
  dataset:
    name: cifar10
    supported_net_types:
    - fc
    - rec
    - conv
    - vgg9
    T: 6
    direct_coding: true
    pin_memory: false
    download: true
    data_root: null
    num_workers: 4
  runtime:
    epochs: 20
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
    batch_size: 256
    progress: true
  optuna: {}
