name: esd_rtrl_fc_snn_cifar10_t8
opt: false
trainer:
  name: esd_rtrl
  supported_net_types:
  - fc
  - rec
  - conv
  lr: 0.0015375920235481753
  use_optimizer: true
  etrace_decay: 0.5905786832075083
  gamma: 0.8756677022116469
  lr_layer_norm:
  - 1.0
  - 1.0
  - 1.0
  detach_state_each_step: true
  debug_unused_learning_signals: false
model:
  name: fc_snn
  net_type: fc
  in_shape:
  - 3072
  hidden_sizes:
  - 1024
  - 512
  num_classes: 10
  beta: 0.9472752364386118
  threshold: 1.4394989415641892
  reset_mechanism: subtract
  out_integrator: true
  algorithm_name: esd_rtrl
dataset:
  name: cifar10
  supported_net_types:
  - fc
  - rec
  - conv
  - vgg9
  T: 6
  seed: 895
  direct_coding: true
  pin_memory: false
  download: true
  data_root: null
  num_workers: 4
runtime:
  epochs: 20
  device: cuda
  seed: 42
  log_level: INFO
  neurobench: false
  batch_size: 256
  progress: true
optuna: {}
