name: etlp_fc_snn_mnist_t8
opt: false
trainer:
  name: etlp
  supported_net_types:
  - fc
  - rec
  lr: 0.0015375920235481753
  surrogate_scale: 0.26636900997297436
  weight_l1: 0.0
  weight_l2: 0.0
  update_rate_hz: 1000.0
  dt_ms: 1.0
  feedback_distribution: normal
  feedback_scale: 1.9422107927526613
  use_optimizer: false
  grad_clip: 0.0
model:
  name: fc_snn
  net_type: fc
  in_shape:
  - 784
  hidden_sizes:
  - 256
  num_classes: 10
  beta: 0.9472752364386118
  threshold: 1.4394989415641892
  reset_mechanism: subtract
  out_integrator: false
  algorithm_name: etlp
dataset:
  name: mnist
  supported_net_types:
  - fc
  - rec
  - conv
  T: 10
  seed: 895
  pin_memory: false
  download: true
  data_root: null
  num_workers: 4
  direct_coding: false
runtime:
  epochs: 20
  device: cuda
  seed: 42
  log_level: INFO
  neurobench: false
  batch_size: 256
  progress: true
optuna: {}
