name: tp_conv_snn_fashionmnist_t7
opt: false
trainer:
  name: tp
  supported_net_types:
  - fc
  - rec
  - conv
  - vgg9
  lr: 4.8280425192712865e-05
  alpha: 0.961409550098685
  beta: 0.8798150834469461
  vth: 1.427398729877027
  surrogate_scale: 1.0
  train_target_propagator: true
  use_optimizer: true
model:
  name: conv_snn
  net_type: conv
  in_shape:
  - 1
  - 28
  - 28
  num_classes: 10
  beta: 0.9700171965812533
  threshold: 1.097899978811085
  out_integrator: true
  algorithm_name: tp
dataset:
  name: fashionmnist
  supported_net_types:
  - fc
  - rec
  - conv
  T: 10
  seed: 922
  pin_memory: false
  download: true
  data_root: null
  num_workers: 4
  direct_coding: false
runtime:
  epochs: 20
  device: cuda
  seed: 42
  log_level: INFO
  neurobench: false
  batch_size: 256
  progress: true
optuna: {}
