name: etlp_fc_snn_svhn_t5
opt: false
trainer:
  name: etlp
  supported_net_types:
  - fc
  - rec
  lr: 0.0026926469100861782
  surrogate_scale: 0.2534717113185624
  weight_l1: 0.0
  weight_l2: 0.0
  update_rate_hz: 1000.0
  dt_ms: 1.0
  feedback_distribution: normal
  feedback_scale: 0.22359802667203107
  use_optimizer: false
  grad_clip: 0.0
model:
  name: fc_snn
  net_type: fc
  in_shape:
  - 3072
  hidden_sizes:
  - 1024
  - 512
  num_classes: 10
  beta: 0.9802882520781333
  threshold: 1.4656320330745594
  reset_mechanism: subtract
  out_integrator: false
  algorithm_name: etlp
dataset:
  name: svhn
  supported_net_types:
  - fc
  - rec
  - conv
  - vgg9
  T: 10
  seed: 809
  direct_coding: true
  pin_memory: false
  download: true
  data_root: null
  num_workers: 4
runtime:
  epochs: 20
  device: cuda
  seed: 42
  log_level: INFO
  neurobench: false
  batch_size: 256
  progress: true
optuna: {}
