
# ══════════════════════════════════════════════════════════════════
#                         M N I S T
# ══════════════════════════════════════════════════════════════════

# ------------- Exp1 ------------- #
decolle_fc_mnist:
  name: decolle_fc_snn_mnist
  opt: false
  trainer:
    name: decolle
    supported_net_types:
    - fc
    - conv
    lr: 0.08178965944163655
    g_scale: 1.9993293071925045
    burn_in: 0
    surrogate: sigmoid
    surrogate_scale: 2.6121082956649895
    delta: 0.2924672658702264
    h_with_noise: false
    omega_std: 0.5
    lambda_u_upper: 0.0
    lambda_u_lower: 0.0
    lr_scale_per_layer: false
  model:
    name: fc_snn
    net_type: fc
    in_shape:
    - 784
    hidden_sizes:
    - 256
    num_classes: 10
    beta: 0.8246808799971943
    threshold: 1.499811914839934
    reset_mechanism: subtract
    out_integrator: false
    algorithm_name: decolle
  dataset:
    name: mnist
    supported_net_types:
    - fc
    - rec
    - conv
    T: 10
    seed: 471
    pin_memory: false
    download: true
    data_root: null
    num_workers: 4
    direct_coding: false
  runtime:
    epochs: 50
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
    batch_size: 256
    progress: false
  optuna: {}

# ------------- Exp2 ------------- #
decolle_conv_mnist:
  name: decolle_conv_snn_mnist
  opt: false
  trainer:
    name: decolle
    supported_net_types:
    - fc
    - conv
    lr: 0.004826019102745669
    g_scale: 0.8730610185453409
    burn_in: 0
    surrogate: sigmoid
    surrogate_scale: 14.19972809677097
    delta: 0.8369969296676002
    h_with_noise: false
    omega_std: 0.5
    lambda_u_upper: 0.0
    lambda_u_lower: 0.0
    lr_scale_per_layer: false
  model:
    name: conv_snn
    net_type: conv
    in_shape:
    - 1
    - 28
    - 28
    num_classes: 10
    beta: 0.8391296139671982
    threshold: 1.4796623055733853
    algorithm_name: decolle
  dataset:
    name: mnist
    supported_net_types:
    - fc
    - rec
    - conv
    T: 10
    seed: 894
    pin_memory: false
    download: true
    data_root: null
    num_workers: 4
    direct_coding: false
  runtime:
    epochs: 50
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
    batch_size: 256
    progress: false
  optuna: {}

# ══════════════════════════════════════════════════════════════════
#                    F a s h i o n - M N I S T
# ══════════════════════════════════════════════════════════════════

# ------------- Exp1 ------------- #
decolle_fc_fashion_mnist:
  name: decolle_fc_snn_fashionmnist
  opt: false
  trainer:
    name: decolle
    supported_net_types:
    - fc
    - conv
    lr: 0.0009689423699327738
    g_scale: 1.7837356254414014
    burn_in: 0
    surrogate: sigmoid
    surrogate_scale: 6.035786384908421
    delta: 0.17610563893477624
    h_with_noise: false
    omega_std: 0.5
    lambda_u_upper: 0.0
    lambda_u_lower: 0.0
    lr_scale_per_layer: false
  model:
    name: fc_snn
    net_type: fc
    in_shape:
    - 784
    hidden_sizes:
    - 800
    num_classes: 10
    beta: 0.9713804775275635
    threshold: 1.303466043881472
    reset_mechanism: subtract
    out_integrator: false
    algorithm_name: decolle
  dataset:
    name: fashionmnist
    supported_net_types:
    - fc
    - rec
    - conv
    T: 10
    seed: 361
    pin_memory: false
    download: true
    data_root: null
    num_workers: 4
    direct_coding: false
  runtime:
    epochs: 50
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
    batch_size: 256
    progress: false
  optuna: {}

# ------------- Exp2 ------------- #
decolle_conv_fashion_mnist:
  name: decolle_conv_snn_fashionmnist_t162
  opt: false
  trainer:
    name: decolle
    supported_net_types:
    - fc
    - conv
    lr: 0.0006857574883880355
    g_scale: 1.8924666516108837
    burn_in: 0
    surrogate: sigmoid
    surrogate_scale: 6.309102868918055
    delta: 0.525431899297452
    h_with_noise: false
    omega_std: 0.5
    lambda_u_upper: 0.0
    lambda_u_lower: 0.0
    lr_scale_per_layer: false
  model:
    name: conv_snn
    net_type: conv
    in_shape:
    - 1
    - 28
    - 28
    num_classes: 10
    beta: 0.9600500566951999
    threshold: 1.349796947034971
    algorithm_name: decolle
  dataset:
    name: fashionmnist
    supported_net_types:
    - fc
    - rec
    - conv
    T: 10
    seed: 370
    pin_memory: false
    download: true
    data_root: null
    num_workers: 4
    direct_coding: false
  runtime:
    epochs: 50
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
    batch_size: 256
    progress: false
  optuna: {}

# ══════════════════════════════════════════════════════════════════
#                        N - M N I S T
# ══════════════════════════════════════════════════════════════════

# ------------- Exp1 ------------- #
decolle_fc_nmnist:
  name: decolle_fc_snn_nmnist
  opt: false
  trainer:
    name: decolle
    supported_net_types:
    - fc
    - conv
    lr: 0.09915874301399447
    g_scale: 1.9523061961008659
    burn_in: 0
    surrogate: sigmoid
    surrogate_scale: 2.583700976551107
    delta: 0.580231964073093
    h_with_noise: false
    omega_std: 0.5
    lambda_u_upper: 0.0
    lambda_u_lower: 0.0
    lr_scale_per_layer: false
  model:
    name: fc_snn
    net_type: fc
    in_shape:
    - 2312
    hidden_sizes:
    - 512
    num_classes: 10
    beta: 0.9104446596558233
    threshold: 1.4613228789684372
    reset_mechanism: subtract
    out_integrator: false
    algorithm_name: decolle
  dataset:
    name: nmnist
    supported_net_types:
    - fc
    - rec
    - conv
    T: 10
    seed: 920
    pin_memory: false
    num_workers: 4
    data_root: null
    download: true
    use_cache: true
  runtime:
    epochs: 50
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
    batch_size: 256
    progress: false
  optuna: {}

# ------------- Exp2 ------------- #
decolle_conv_nmnist:
  name: decolle_conv_snn_nmnist
  opt: false
  trainer:
    name: decolle
    supported_net_types:
    - fc
    - conv
    lr: 0.005614483155999641
    g_scale: 1.9255390052504073
    burn_in: 0
    surrogate: sigmoid
    surrogate_scale: 15.62183562821011
    delta: 0.8171420354020845
    h_with_noise: false
    omega_std: 0.5
    lambda_u_upper: 0.0
    lambda_u_lower: 0.0
    lr_scale_per_layer: false
  model:
    name: conv_snn
    net_type: conv
    in_shape:
    - 2
    - 34
    - 34
    num_classes: 10
    beta: 0.9501719071645311
    threshold: 1.4997465378509036
    algorithm_name: decolle
  dataset:
    name: nmnist
    supported_net_types:
    - fc
    - rec
    - conv
    T: 10
    seed: 375
    pin_memory: false
    num_workers: 4
    data_root: null
    download: true
    use_cache: true
  runtime:
    epochs: 50
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
    batch_size: 256
    progress: false
  optuna: {}

# ══════════════════════════════════════════════════════════════════
#                        C I F A R - 1 0
# ══════════════════════════════════════════════════════════════════

# ------------- Exp1 ------------- #
decolle_fc_cifar10:
  name: decolle_fc_snn_cifar10
  opt: false
  trainer:
    name: decolle
    supported_net_types:
    - fc
    - conv
    lr: 0.09924283629158077
    g_scale: 0.8802487653260564
    burn_in: 0
    surrogate: sigmoid
    surrogate_scale: 2.8994752345444037
    delta: 0.19785764779536372
    h_with_noise: false
    omega_std: 0.5
    lambda_u_upper: 0.0
    lambda_u_lower: 0.0
    lr_scale_per_layer: false
  model:
    name: fc_snn
    net_type: fc
    in_shape:
    - 3072
    hidden_sizes:
    - 1024
    - 512
    num_classes: 10
    beta: 0.8470547344083026
    threshold: 1.1781164704083602
    reset_mechanism: subtract
    out_integrator: false
    algorithm_name: decolle
  dataset:
    name: cifar10
    supported_net_types:
    - fc
    - rec
    - conv
    - vgg9
    T: 6
    seed: 124
    direct_coding: true
    pin_memory: false
    download: true
    data_root: null
    num_workers: 4
  runtime:
    epochs: 50
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
    batch_size: 256
    progress: false
  optuna: {}

# ------------- Exp2 ------------- #
decolle_conv_cifar10:
  name: decolle_conv_snn_cifar10
  opt: false
  trainer:
    name: decolle
    supported_net_types:
    - fc
    - conv
    lr: 0.009226987081668204
    g_scale: 1.3096678276991267
    burn_in: 0
    surrogate: sigmoid
    surrogate_scale: 4.44233022966138
    delta: 0.5472960791933985
    h_with_noise: false
    omega_std: 0.5
    lambda_u_upper: 0.0
    lambda_u_lower: 0.0
    lr_scale_per_layer: false
  model:
    name: conv_snn
    net_type: conv
    in_shape:
    - 3
    - 32
    - 32
    num_classes: 10
    beta: 0.8000547367585011
    threshold: 0.9207626741525745
    algorithm_name: decolle
  dataset:
    name: cifar10
    supported_net_types:
    - fc
    - rec
    - conv
    - vgg9
    T: 6
    seed: 91
    direct_coding: true
    pin_memory: false
    download: true
    data_root: null
    num_workers: 4
  runtime:
    epochs: 50
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
    batch_size: 256
    progress: false
  optuna: {}

# ══════════════════════════════════════════════════════════════════
#                          S V H N
# ══════════════════════════════════════════════════════════════════


# ══════════════════════════════════════════════════════════════════
#                      D V S - C I F A R 1 0
# ══════════════════════════════════════════════════════════════════

# ------------- Exp1 ------------- #
decolle_fc_dvs_cifar10:
  name: decolle_fc_snn_dvscifar10
  opt: false
  trainer:
    name: decolle
    supported_net_types:
    - fc
    - conv
    lr: 0.07538604659431389
    g_scale: 0.89041259915257
    burn_in: 0
    surrogate: sigmoid
    surrogate_scale: 3.8983484248521956
    delta: 0.6408507112352599
    h_with_noise: false
    omega_std: 0.5
    lambda_u_upper: 0.0
    lambda_u_lower: 0.0
    lr_scale_per_layer: false
  model:
    name: fc_snn
    net_type: fc
    in_shape:
    - 32768
    hidden_sizes:
    - 1024
    - 512
    num_classes: 10
    beta: 0.8592744019449933
    threshold: 0.9015524503432497
    reset_mechanism: subtract
    out_integrator: false
    algorithm_name: decolle
  dataset:
    name: dvscifar10
    supported_net_types:
    - fc
    - rec
    - conv
    - vgg9
    T: 10
    seed: 348
    pin_memory: false
    num_workers: 4
    train_fraction: 0.9
    data_root: null
    download: true
    use_cache: true
  runtime:
    epochs: 50
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
    batch_size: 256
    progress: false
  optuna: {}

# ------------- Exp2 ------------- #
decolle_conv_dvs_cifar10:
  name: decolle_conv_snn_dvscifar10
  opt: false
  trainer:
    name: decolle
    supported_net_types:
    - fc
    - conv
    lr: 0.0011341054259189538
    g_scale: 1.4416539387158864
    burn_in: 0
    surrogate: sigmoid
    surrogate_scale: 19.42120510496945
    delta: 0.9390613077206084
    h_with_noise: false
    omega_std: 0.5
    lambda_u_upper: 0.0
    lambda_u_lower: 0.0
    lr_scale_per_layer: false
  model:
    name: conv_snn
    net_type: conv
    in_shape:
    - 2
    - 128
    - 128
    num_classes: 10
    beta: 0.8029198700923399
    threshold: 0.8980433422201766
    algorithm_name: decolle
  dataset:
    name: dvscifar10
    supported_net_types:
    - fc
    - rec
    - conv
    - vgg9
    T: 10
    seed: 16
    pin_memory: false
    num_workers: 4
    train_fraction: 0.9
    data_root: null
    download: true
    use_cache: true
  runtime:
    epochs: 50
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
    batch_size: 256
    progress: false
  optuna: {}

# ══════════════════════════════════════════════════════════════════
#                      D V S - G e s t u r e
# ══════════════════════════════════════════════════════════════════

# ------------- Exp1 ------------- #
decolle_fc_dvs_gesture:
  name: decolle_fc_snn_dvsgesture
  opt: false
  trainer:
    name: decolle
    supported_net_types:
    - fc
    - conv
    lr: 0.06445359572281745
    g_scale: 1.774660456140336
    burn_in: 0
    surrogate: sigmoid
    surrogate_scale: 2.7540963640513865
    delta: 0.7021338604961964
    h_with_noise: false
    omega_std: 0.5
    lambda_u_upper: 0.0
    lambda_u_lower: 0.0
    lr_scale_per_layer: false
  model:
    name: fc_snn
    net_type: fc
    in_shape:
    - 32768
    hidden_sizes:
    - 2048
    num_classes: 11
    beta: 0.9357428007400196
    threshold: 1.1789233160379988
    reset_mechanism: subtract
    out_integrator: false
    algorithm_name: decolle
  dataset:
    name: dvsgesture
    supported_net_types:
    - fc
    - rec
    - conv
    - vgg9
    T: 20
    seed: 275
    pin_memory: false
    num_workers: 4
    data_root: null
    download: true
    use_cache: true
  runtime:
    epochs: 50
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
    batch_size: 256
    progress: false
  optuna: {}

# ------------- Exp2 ------------- #
decolle_conv_dvs_gesture:
  name: decolle_conv_snn_dvsgesture
  opt: false
  trainer:
    name: decolle
    supported_net_types:
    - fc
    - conv
    lr: 0.002753504293196722
    g_scale: 1.9601999411154938
    burn_in: 0
    surrogate: sigmoid
    surrogate_scale: 8.018273325322982
    delta: 0.4837769202854245
    h_with_noise: false
    omega_std: 0.5
    lambda_u_upper: 0.0
    lambda_u_lower: 0.0
    lr_scale_per_layer: false
  model:
    name: conv_snn
    net_type: conv
    in_shape:
    - 2
    - 128
    - 128
    num_classes: 11
    beta: 0.9041685868696188
    threshold: 0.8291435749252959
    algorithm_name: decolle
  dataset:
    name: dvsgesture
    supported_net_types:
    - fc
    - rec
    - conv
    - vgg9
    T: 20
    seed: 523
    pin_memory: false
    num_workers: 4
    data_root: null
    download: true
    use_cache: true
  runtime:
    epochs: 50
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
    batch_size: 256
    progress: false
  optuna: {}

# ══════════════════════════════════════════════════════════════════
#                          S H D
# ══════════════════════════════════════════════════════════════════
