
# ══════════════════════════════════════════════════════════════
#                             MNIST                            
# ══════════════════════════════════════════════════════════════
# ───────────── Exp1 ───────────── #
esd_rtrl_fc_mnist:
  name: esd_rtrl_fc_snn_mnist
  opt: false
  trainer:
    name: esd_rtrl
    supported_net_types:
    - fc
    - rec
    - conv
    lr: 0.0024839175019342485
    use_optimizer: true
    etrace_decay: 0.656766158023483
    gamma: 0.631351253404753
    lr_layer_norm:
    - 1.0
    - 1.0
    - 1.0
    detach_state_each_step: true
    debug_unused_learning_signals: false
  model:
    name: fc_snn
    net_type: fc
    in_shape:
    - 784
    hidden_sizes:
    - 256
    num_classes: 10
    beta: 0.8007761121170582
    threshold: 0.7194825296639781
    reset_mechanism: subtract
    out_integrator: false
    algorithm_name: esd_rtrl
  dataset:
    name: mnist
    supported_net_types:
    - fc
    - rec
    - conv
    T: 10
    seed: 518
    pin_memory: false
    download: true
    data_root: null
    num_workers: 4
    direct_coding: false
  runtime:
    epochs: 50
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
    batch_size: 256
    progress: false
  optuna: {}

# ───────────── Exp2 ───────────── #
esd_rtrl_r_mnist:
  name: esd_rtrl_r_snn_mnist
  opt: false
  trainer:
    name: esd_rtrl
    supported_net_types:
    - fc
    - rec
    - conv
    lr: 0.0011804923948158948
    use_optimizer: true
    etrace_decay: 0.5008188363023777
    gamma: 0.3007161102645958
    lr_layer_norm:
    - 1.0
    - 1.0
    - 1.0
    detach_state_each_step: true
    debug_unused_learning_signals: false
  model:
    name: r_snn
    net_type: rec
    in_shape:
    - 784
    hidden_sizes:
    - 256
    num_classes: 10
    beta: 0.8849022961425369
    threshold: 0.6118381365842492
    reset_mechanism: subtract
    out_integrator: false
    algorithm_name: esd_rtrl
  dataset:
    name: mnist
    supported_net_types:
    - fc
    - rec
    - conv
    T: 10
    seed: 171
    pin_memory: false
    download: true
    data_root: null
    num_workers: 4
    direct_coding: false
  runtime:
    epochs: 50
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
    batch_size: 256
    progress: false
  optuna: {}

# ───────────── Exp3 ───────────── #
esd_rtrl_conv_mnist:
  name: esd_rtrl_conv_snn_mnist
  opt: false
  trainer:
    name: esd_rtrl
    supported_net_types:
    - fc
    - rec
    - conv
    lr: 0.0025674950044195393
    use_optimizer: true
    etrace_decay: 0.6038242390398365
    gamma: 0.3452078563748387
    lr_layer_norm:
    - 1.0
    - 1.0
    - 1.0
    detach_state_each_step: true
    debug_unused_learning_signals: false
  model:
    name: conv_snn
    net_type: conv
    in_shape:
    - 1
    - 28
    - 28
    num_classes: 10
    beta: 0.8167603219395613
    threshold: 0.6374972175517696
    algorithm_name: esd_rtrl
  dataset:
    name: mnist
    supported_net_types:
    - fc
    - rec
    - conv
    T: 10
    seed: 534
    pin_memory: false
    download: true
    data_root: null
    num_workers: 4
    direct_coding: false
  runtime:
    epochs: 50
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
    batch_size: 256
    progress: false
  optuna: {}


# ══════════════════════════════════════════════════════════════
#                          FashionMNIST                        
# ══════════════════════════════════════════════════════════════
# ───────────── Exp1 ───────────── #
esd_rtrl_fc_fmnist:
  name: esd_rtrl_fc_snn_fashionmnist
  opt: false
  trainer:
    name: esd_rtrl
    supported_net_types:
    - fc
    - rec
    - conv
    lr: 0.0005207083757877279
    use_optimizer: true
    etrace_decay: 0.5740545081611195
    gamma: 0.3511367123835285
    lr_layer_norm:
    - 1.0
    - 1.0
    - 1.0
    detach_state_each_step: true
    debug_unused_learning_signals: false
  model:
    name: fc_snn
    net_type: fc
    in_shape:
    - 784
    hidden_sizes:
    - 800
    num_classes: 10
    beta: 0.804295739110599
    threshold: 0.6799750103164919
    reset_mechanism: subtract
    out_integrator: false
    algorithm_name: esd_rtrl
  dataset:
    name: fashionmnist
    supported_net_types:
    - fc
    - rec
    - conv
    T: 10
    seed: 358
    pin_memory: false
    download: true
    data_root: null
    num_workers: 4
    direct_coding: false
  runtime:
    epochs: 50
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
    batch_size: 256
    progress: false
  optuna: {}

# ───────────── Exp2 ───────────── #
esd_rtrl_r_fmnist:
  name: esd_rtrl_r_snn_fashionmnist
  opt: false
  trainer:
    name: esd_rtrl
    supported_net_types:
    - fc
    - rec
    - conv
    lr: 0.0004980428670367971
    use_optimizer: true
    etrace_decay: 0.6464201985530867
    gamma: 0.7261461923299879
    lr_layer_norm:
    - 1.0
    - 1.0
    - 1.0
    detach_state_each_step: true
    debug_unused_learning_signals: false
  model:
    name: r_snn
    net_type: rec
    in_shape:
    - 784
    hidden_sizes:
    - 256
    num_classes: 10
    beta: 0.9591256898106965
    threshold: 1.1266136910579048
    reset_mechanism: subtract
    out_integrator: false
    algorithm_name: esd_rtrl
  dataset:
    name: fashionmnist
    supported_net_types:
    - fc
    - rec
    - conv
    T: 10
    seed: 128
    pin_memory: false
    download: true
    data_root: null
    num_workers: 4
    direct_coding: false
  runtime:
    epochs: 50
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
    batch_size: 256
    progress: false
  optuna: {}

# ───────────── Exp3 ───────────── #
esd_rtrl_conv_fmnist:
  name: esd_rtrl_conv_snn_fashionmnist
  opt: false
  trainer:
    name: esd_rtrl
    supported_net_types:
    - fc
    - rec
    - conv
    lr: 0.0006362673580571818
    use_optimizer: true
    etrace_decay: 0.55795383094694
    gamma: 0.34821332722350423
    lr_layer_norm:
    - 1.0
    - 1.0
    - 1.0
    detach_state_each_step: true
    debug_unused_learning_signals: false
  model:
    name: conv_snn
    net_type: conv
    in_shape:
    - 1
    - 28
    - 28
    num_classes: 10
    beta: 0.8209176553897997
    threshold: 0.5840448056479814
    algorithm_name: esd_rtrl
  dataset:
    name: fashionmnist
    supported_net_types:
    - fc
    - rec
    - conv
    T: 10
    seed: 391
    pin_memory: false
    download: true
    data_root: null
    num_workers: 4
    direct_coding: false
  runtime:
    epochs: 5
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
    batch_size: 256
    progress: false
  optuna: {}

# ══════════════════════════════════════════════════════════════
#                              SVHN                            
# ══════════════════════════════════════════════════════════════
# ───────────── Exp1 ───────────── #
esd_rtrl_fc_svhn:
  name: esd_rtrl_fc_snn_svhn
  opt: false
  trainer:
    name: esd_rtrl
    supported_net_types:
    - fc
    - rec
    - conv
    lr: 6.673695325576219e-05
    use_optimizer: true
    etrace_decay: 0.5252908218069358
    gamma: 0.2009582044062672
    lr_layer_norm:
    - 1.0
    - 1.0
    - 1.0
    detach_state_each_step: true
    debug_unused_learning_signals: false
  model:
    name: fc_snn
    net_type: fc
    in_shape:
    - 3072
    hidden_sizes:
    - 1024
    - 512
    num_classes: 10
    beta: 0.8132317980471014
    threshold: 0.6916224505152035
    reset_mechanism: subtract
    out_integrator: false
    algorithm_name: esd_rtrl
  dataset:
    name: svhn
    supported_net_types:
    - fc
    - rec
    - conv
    - vgg9
    T: 10
    seed: 724
    direct_coding: true
    pin_memory: false
    download: true
    data_root: null
    num_workers: 4
  runtime:
    epochs: 50
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
    batch_size: 256
    progress: false
  optuna: {}


# ══════════════════════════════════════════════════════════════
#                            CIFAR10                           
# ══════════════════════════════════════════════════════════════
# ───────────── Exp1 ───────────── #
esd_rtrl_fc_cifar10:
  name: esd_rtrl_fc_snn_cifar10
  opt: false
  trainer:
    name: esd_rtrl
    supported_net_types:
    - fc
    - rec
    - conv
    lr: 4.249069238736915e-05
    use_optimizer: true
    etrace_decay: 0.5306013946480688
    gamma: 0.5190232910621115
    lr_layer_norm:
    - 1.0
    - 1.0
    - 1.0
    detach_state_each_step: true
    debug_unused_learning_signals: false
  model:
    name: fc_snn
    net_type: fc
    in_shape:
    - 3072
    hidden_sizes:
    - 1024
    - 512
    num_classes: 10
    beta: 0.805216922495808
    threshold: 0.7056291833384085
    reset_mechanism: subtract
    out_integrator: false
    algorithm_name: esd_rtrl
  dataset:
    name: cifar10
    supported_net_types:
    - fc
    - rec
    - conv
    - vgg9
    T: 6
    seed: 788
    direct_coding: true
    pin_memory: false
    download: true
    data_root: null
    num_workers: 4
  runtime:
    epochs: 50
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
    batch_size: 256
    progress: false
  optuna: {}

# ───────────── Exp2 ───────────── #
esd_rtrl_r_cifar10:
  name: esd_rtrl_r_snn_cifar10
  opt: false
  trainer:
    name: esd_rtrl
    supported_net_types:
    - fc
    - rec
    - conv
    lr: 0.00043853354736888363
    use_optimizer: true
    etrace_decay: 0.9440019205259539
    gamma: 0.8117258271043193
    lr_layer_norm:
    - 1.0
    - 1.0
    - 1.0
    detach_state_each_step: true
    debug_unused_learning_signals: false
  model:
    name: r_snn
    net_type: rec
    in_shape:
    - 3072
    hidden_sizes:
    - 512
    - 256
    num_classes: 10
    beta: 0.8079566568013559
    threshold: 0.7540672974066885
    reset_mechanism: subtract
    out_integrator: false
    algorithm_name: esd_rtrl
  dataset:
    name: cifar10
    supported_net_types:
    - fc
    - rec
    - conv
    - vgg9
    T: 6
    seed: 78
    direct_coding: true
    pin_memory: false
    download: true
    data_root: null
    num_workers: 4
  runtime:
    epochs: 50
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
    batch_size: 256
    progress: false
  optuna: {}

# ───────────── Exp3 ───────────── #
esd_rtrl_conv_cifar10:
  name: esd_rtrl_conv_snn_cifar10
  opt: false
  trainer:
    name: esd_rtrl
    supported_net_types:
    - fc
    - rec
    - conv
    lr: 0.00044729041272417974
    use_optimizer: true
    etrace_decay: 0.7100194802294586
    gamma: 0.2061870894430053
    lr_layer_norm:
    - 1.0
    - 1.0
    - 1.0
    detach_state_each_step: true
    debug_unused_learning_signals: false
  model:
    name: conv_snn
    net_type: conv
    in_shape:
    - 3
    - 32
    - 32
    num_classes: 10
    beta: 0.8172485295879716
    threshold: 0.6404794344571783
    algorithm_name: esd_rtrl
  dataset:
    name: cifar10
    supported_net_types:
    - fc
    - rec
    - conv
    - vgg9
    T: 6
    seed: 567
    direct_coding: true
    pin_memory: false
    download: true
    data_root: null
    num_workers: 4
  runtime:
    epochs: 5
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
    batch_size: 256
    progress: false
  optuna: {}

# ══════════════════════════════════════════════════════════════════
#                      D V S - C I F A R 1 0
# ══════════════════════════════════════════════════════════════════

# ───────────── Exp1 ───────────── #
esd_rtrl_fc_dvscifar10:
  name: esd_rtrl_fc_snn_dvscifar10
  opt: false
  trainer:
    name: esd_rtrl
    supported_net_types:
    - fc
    - rec
    - conv
    lr: 1.8347035793002367e-05
    use_optimizer: true
    etrace_decay: 0.6937625075043004
    gamma: 0.7920892730101835
    lr_layer_norm:
    - 1.0
    - 1.0
    - 1.0
    detach_state_each_step: true
    debug_unused_learning_signals: false
  model:
    name: fc_snn
    net_type: fc
    in_shape:
    - 32768
    hidden_sizes:
    - 1024
    - 512
    num_classes: 10
    beta: 0.8181508499438089
    threshold: 0.5492385951569427
    reset_mechanism: subtract
    out_integrator: false
    algorithm_name: esd_rtrl
  dataset:
    name: dvscifar10
    supported_net_types:
    - fc
    - rec
    - conv
    - vgg9
    T: 10
    seed: 642
    pin_memory: false
    num_workers: 4
    train_fraction: 0.9
    data_root: null
    download: true
    use_cache: true
  runtime:
    epochs: 5
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
    batch_size: 256
    progress: false
  optuna: {}

# ══════════════════════════════════════════════════════════════
#                           DVSGesture                         
# ══════════════════════════════════════════════════════════════
# ───────────── Exp1 ───────────── #
esd_rtrl_fc_dvsgesture:
  name: esd_rtrl_fc_snn_dvsgesture
  opt: false
  trainer:
    name: esd_rtrl
    supported_net_types:
    - fc
    - rec
    - conv
    lr: 0.0002989959847003977
    use_optimizer: true
    etrace_decay: 0.569350347465629
    gamma: 0.16289014664718682
    lr_layer_norm:
    - 1.0
    - 1.0
    - 1.0
    detach_state_each_step: true
    debug_unused_learning_signals: false
  model:
    name: fc_snn
    net_type: fc
    in_shape:
    - 32768
    hidden_sizes:
    - 2048
    num_classes: 11
    beta: 0.8199630251493876
    threshold: 1.2620628126132443
    reset_mechanism: subtract
    out_integrator: false
    algorithm_name: esd_rtrl
  dataset:
    name: dvsgesture
    supported_net_types:
    - fc
    - rec
    - conv
    - vgg9
    T: 20
    seed: 692
    pin_memory: false
    num_workers: 4
    data_root: null
    download: true
    use_cache: true
  runtime:
    epochs: 50
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
    batch_size: 256
    progress: false
  optuna: {}

# ───────────── Exp2 ───────────── #
esd_rtrl_r_dvsgesture:
  name: esd_rtrl_r_snn_dvsgesture
  opt: false
  trainer:
    name: esd_rtrl
    supported_net_types:
    - fc
    - rec
    - conv
    lr: 0.002890170189282254
    use_optimizer: true
    etrace_decay: 0.6111106229434761
    gamma: 0.22868407465055493
    lr_layer_norm:
    - 1.0
    - 1.0
    - 1.0
    detach_state_each_step: true
    debug_unused_learning_signals: false
  model:
    name: r_snn
    net_type: rec
    in_shape:
    - 32768
    hidden_sizes:
    - 1024
    num_classes: 11
    beta: 0.8130250457165551
    threshold: 0.5410159275915709
    reset_mechanism: subtract
    out_integrator: false
    algorithm_name: esd_rtrl
  dataset:
    name: dvsgesture
    supported_net_types:
    - fc
    - rec
    - conv
    - vgg9
    T: 20
    seed: 514
    pin_memory: false
    num_workers: 4
    data_root: null
    download: true
    use_cache: true
  runtime:
    epochs: 50
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
    batch_size: 256
    progress: false
  optuna: {}

# ───────────── Exp3 ───────────── #
esd_rtrl_conv_dvsgesture:
  name: esd_rtrl_conv_snn_dvsgesture
  opt: false
  trainer:
    name: esd_rtrl
    supported_net_types:
    - fc
    - rec
    - conv
    lr: 0.0024343574529552825
    use_optimizer: true
    etrace_decay: 0.7575196880195149
    gamma: 0.7981294612212474
    lr_layer_norm:
    - 1.0
    - 1.0
    - 1.0
    detach_state_each_step: true
    debug_unused_learning_signals: false
  model:
    name: conv_snn
    net_type: conv
    in_shape:
    - 2
    - 128
    - 128
    num_classes: 11
    beta: 0.8120768977092567
    threshold: 0.5370359749948321
    algorithm_name: esd_rtrl
  dataset:
    name: dvsgesture
    supported_net_types:
    - fc
    - rec
    - conv
    - vgg9
    T: 20
    seed: 25
    pin_memory: false
    num_workers: 4
    data_root: null
    download: true
    use_cache: true
  runtime:
    epochs: 5
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
    batch_size: 256
    progress: false
  optuna: {}
