
# ══════════════════════════════════════════════════════════════════
#                         M N I S T
# ══════════════════════════════════════════════════════════════════

osttp_fc_snn_mnist:
  name: osttp_fc_snn_mnist
  opt: false
  trainer:
    name: osttp
    supported_net_types:
    - fc
    - rec
    lr: 0.0035813213443545077
    batch_size: 512
    pseudo: tanh
    output_loss: mse
    feedback_scale: 1.6702678618895757
    feedback_seed: 42
    grad_clip: 0.0
    use_optimizer: true
  model:
    name: fc_snn
    net_type: fc
    in_shape:
    - 784
    hidden_sizes:
    - 256
    num_classes: 10
    beta: 0.8001805197467812
    threshold: 0.6382157726657275
    reset_mechanism: subtract
    out_integrator: false
    algorithm_name: osttp
  dataset:
    name: mnist
    supported_net_types:
    - fc
    - rec
    - conv
    batch_size: 64
    T: 10
    seed: 773
    pin_memory: false
    download: true
    data_root: null
    num_workers: 4
  runtime:
    epochs: 5
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
  optuna: {}

osttp_r_snn_mnist:
  name: osttp_r_snn_mnist
  opt: false
  trainer:
    name: osttp
    supported_net_types:
    - fc
    - rec
    lr: 0.0006219450761968131
    batch_size: 256
    pseudo: fast_sigmoid
    output_loss: mse
    feedback_scale: 1.8922480971092592
    feedback_seed: 42
    grad_clip: 0.0
    use_optimizer: true
  model:
    name: r_snn
    net_type: rec
    in_shape:
    - 784
    hidden_sizes:
    - 256
    num_classes: 10
    beta: 0.9334419941351061
    threshold: 0.5481350484450342
    reset_mechanism: subtract
    out_integrator: false
    algorithm_name: osttp
  dataset:
    name: mnist
    supported_net_types:
    - fc
    - rec
    - conv
    batch_size: 64
    T: 10
    seed: 32
    pin_memory: false
    download: true
    data_root: null
    num_workers: 4
  runtime:
    epochs: 5
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
  optuna: {}

# ══════════════════════════════════════════════════════════════════
#                    F a s h i o n - M N I S T
# ══════════════════════════════════════════════════════════════════

osttp_fc_snn_fashionmnist:
  name: osttp_fc_snn_fashionmnist
  opt: false
  trainer:
    name: osttp
    supported_net_types:
    - fc
    - rec
    lr: 0.0026701122818478633
    batch_size: 128
    pseudo: tanh
    output_loss: mse
    feedback_scale: 0.1458690896065188
    feedback_seed: 42
    grad_clip: 0.0
    use_optimizer: true
  model:
    name: fc_snn
    net_type: fc
    in_shape:
    - 784
    hidden_sizes:
    - 800
    num_classes: 10
    beta: 0.9250359306685366
    threshold: 0.9792171145183827
    reset_mechanism: subtract
    out_integrator: false
    algorithm_name: osttp
  dataset:
    name: fashionmnist
    supported_net_types:
    - fc
    - rec
    - conv
    batch_size: 128
    T: 10
    seed: 712
    pin_memory: false
    download: true
    data_root: null
    num_workers: 4
  runtime:
    epochs: 5
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
  optuna: {}

osttp_r_snn_fashionmnist:
  name: osttp_r_snn_fashionmnist
  opt: false
  trainer:
    name: osttp
    supported_net_types:
    - fc
    - rec
    lr: 0.0006414139409437252
    batch_size: 256
    pseudo: fast_sigmoid
    output_loss: mse
    feedback_scale: 1.7514967576029683
    feedback_seed: 42
    grad_clip: 0.0
    use_optimizer: true
  model:
    name: r_snn
    net_type: rec
    in_shape:
    - 784
    hidden_sizes:
    - 256
    num_classes: 10
    beta: 0.8237029086548829
    threshold: 0.507547583630606
    reset_mechanism: subtract
    out_integrator: false
    algorithm_name: osttp
  dataset:
    name: fashionmnist
    supported_net_types:
    - fc
    - rec
    - conv
    batch_size: 256
    T: 10
    seed: 987
    pin_memory: false
    download: true
    data_root: null
    num_workers: 4
  runtime:
    epochs: 5
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
  optuna: {}

# ══════════════════════════════════════════════════════════════════
#                        N - M N I S T
# ══════════════════════════════════════════════════════════════════

osttp_fc_snn_nmnist:
  name: osttp_fc_snn_nmnist
  opt: false
  trainer:
    name: osttp
    supported_net_types:
    - fc
    - rec
    lr: 0.0002606355137649041
    batch_size: 256
    pseudo: fast_sigmoid
    output_loss: mse
    feedback_scale: 0.7910435355140856
    feedback_seed: 42
    grad_clip: 0.0
    use_optimizer: true
  model:
    name: fc_snn
    net_type: fc
    in_shape:
    - 2312
    hidden_sizes:
    - 512
    num_classes: 10
    beta: 0.9639608370939672
    threshold: 0.5965088762746591
    reset_mechanism: subtract
    out_integrator: false
    algorithm_name: osttp
  dataset:
    name: nmnist
    supported_net_types:
    - fc
    - rec
    - conv
    batch_size: 32
    T: 50
    seed: 561
    pin_memory: false
    num_workers: 4
    data_root: null
    download: true
  runtime:
    epochs: 5
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
  optuna: {}

# ══════════════════════════════════════════════════════════════════
#                        C I F A R - 1 0
# ══════════════════════════════════════════════════════════════════

osttp_fc_snn_cifar10:
  name: osttp_fc_snn_cifar10
  opt: false
  trainer:
    name: osttp
    supported_net_types:
    - fc
    - rec
    lr: 0.0001031711372132112
    batch_size: 128
    pseudo: tanh
    output_loss: mse
    feedback_scale: 1.3837353093368463
    feedback_seed: 42
    grad_clip: 0.0
    use_optimizer: true
  model:
    name: fc_snn
    net_type: fc
    in_shape:
    - 3072
    hidden_sizes:
    - 1024
    - 512
    num_classes: 10
    beta: 0.9230553378973694
    threshold: 0.5083074119062545
    reset_mechanism: subtract
    out_integrator: false
    algorithm_name: osttp
  dataset:
    name: cifar10
    supported_net_types:
    - fc
    - rec
    - conv
    - vgg9
    batch_size: 64
    T: 10
    seed: 138
    direct_coding: true
    pin_memory: false
    download: true
    data_root: null
    num_workers: 4
  runtime:
    epochs: 5
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
  optuna: {}

osttp_r_snn_cifar10:
  name: osttp_r_snn_cifar10
  opt: false
  trainer:
    name: osttp
    supported_net_types:
    - fc
    - rec
    lr: 0.000275949068443324
    batch_size: 128
    pseudo: tanh
    output_loss: mse
    feedback_scale: 1.9866581705533137
    feedback_seed: 42
    grad_clip: 0.0
    use_optimizer: true
  model:
    name: r_snn
    net_type: rec
    in_shape:
    - 3072
    hidden_sizes:
    - 512
    - 256
    num_classes: 10
    beta: 0.8747624532065823
    threshold: 0.5045641228537181
    reset_mechanism: subtract
    out_integrator: false
    algorithm_name: osttp
  dataset:
    name: cifar10
    supported_net_types:
    - fc
    - rec
    - conv
    - vgg9
    batch_size: 64
    T: 10
    seed: 214
    direct_coding: true
    pin_memory: false
    download: true
    data_root: null
    num_workers: 4
  runtime:
    epochs: 5
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
  optuna: {}

# ══════════════════════════════════════════════════════════════════
#                          S V H N
# ══════════════════════════════════════════════════════════════════

osttp_fc_snn_svhn:
  name: osttp_fc_snn_svhn
  opt: false
  trainer:
    name: osttp
    supported_net_types:
    - fc
    - rec
    lr: 3.619247605469855e-05
    batch_size: 512
    pseudo: tanh
    output_loss: ce
    feedback_scale: 0.9833441218148523
    feedback_seed: 42
    grad_clip: 0.0
    use_optimizer: true
  model:
    name: fc_snn
    net_type: fc
    in_shape:
    - 3072
    hidden_sizes:
    - 1024
    - 512
    num_classes: 10
    beta: 0.8118161183148689
    threshold: 1.3625530444422613
    reset_mechanism: subtract
    out_integrator: false
    algorithm_name: osttp
  dataset:
    name: svhn
    supported_net_types:
    - fc
    - rec
    - conv
    - vgg9
    batch_size: 64
    T: 10
    seed: 221
    direct_coding: true
    pin_memory: false
    download: true
    data_root: null
    num_workers: 4
  runtime:
    epochs: 5
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
  optuna: {}

# ══════════════════════════════════════════════════════════════════
#                      D V S - C I F A R 1 0
# ══════════════════════════════════════════════════════════════════


# ══════════════════════════════════════════════════════════════════
#                      D V S - G e s t u r e
# ══════════════════════════════════════════════════════════════════


# ══════════════════════════════════════════════════════════════════
#                          S H D
# ══════════════════════════════════════════════════════════════════
