
# ══════════════════════════════════════════════════════════════════
#                         M N I S T
# ══════════════════════════════════════════════════════════════════


# ══════════════════════════════════════════════════════════════════
#                    F a s h i o n - M N I S T
# ══════════════════════════════════════════════════════════════════


# ══════════════════════════════════════════════════════════════════
#                        N - M N I S T
# ══════════════════════════════════════════════════════════════════


# ══════════════════════════════════════════════════════════════════
#                        C I F A R - 1 0
# ══════════════════════════════════════════════════════════════════


# ══════════════════════════════════════════════════════════════════
#                          S V H N
# ══════════════════════════════════════════════════════════════════


# ══════════════════════════════════════════════════════════════════
#                      D V S - C I F A R 1 0
# ══════════════════════════════════════════════════════════════════


# ══════════════════════════════════════════════════════════════════
#                      D V S - G e s t u r e
# ══════════════════════════════════════════════════════════════════


# ══════════════════════════════════════════════════════════════════
#                          S H D
# ══════════════════════════════════════════════════════════════════
