name: bptt_conv_snn_dvscifar10_t1
opt: false
trainer:
  name: bptt
  supported_net_types:
  - fc
  - rec
  - conv
  lr: 4.207988669606632e-05
  loss_type: ce_rate
  grad_clip: null
  use_optimizer: true
model:
  name: conv_snn
  net_type: conv
  in_shape:
  - 2
  - 128
  - 128
  num_classes: 10
  beta: 0.8296389588638785
  threshold: 0.5580836121681995
  algorithm_name: bptt
dataset:
  name: dvscifar10
  supported_net_types:
  - fc
  - rec
  - conv
  - vgg9
  T: 10
  seed: 867
  pin_memory: false
  num_workers: 4
  train_fraction: 0.9
  data_root: null
  download: true
  use_cache: true
runtime:
  epochs: 20
  device: cuda
  seed: 42
  log_level: INFO
  neurobench: false
  batch_size: 256
  progress: true
optuna: {}
