eprop_r_snn_svhn_t1:
  name: eprop_r_snn_svhn_t1
  opt: false
  trainer:
    name: eprop
    supported_net_types:
    - rec
    lr: 4.207988669606632e-05
    gamma: 0.16239780813448107
    dt: null
    tau_mem: null
    tau_out: null
    threshold: null
    lr_layer_norm:
    - 1.0
    - 1.0
    - 1.0
    use_optimizer: true
    update_last: false
    update_every: 1
    seq_batch_size: 1
  model:
    name: r_snn
    net_type: rec
    in_shape:
    - 3072
    hidden_sizes:
    - 512
    num_classes: 10
    beta: 0.8110358863119579
    threshold: 1.366176145774935
    reset_mechanism: subtract
    out_integrator: true
    algorithm_name: eprop
  dataset:
    name: svhn
    supported_net_types:
    - fc
    - rec
    - conv
    - vgg9
    T: 10
    direct_coding: true
    pin_memory: false
    download: true
    data_root: null
    num_workers: 4
  runtime:
    epochs: 20
    device: cuda
    seed: 42
    log_level: INFO
    neurobench: false
    batch_size: 64
    progress: true
  optuna: {}
