name: decolle_conv_snn_mnist_t0
opt: false
trainer:
  name: decolle
  supported_net_types:
  - fc
  - conv
  lr: 0.00031489116479568613
  g_scale: 1.9063571821788408
  burn_in: 0
  surrogate: sigmoid
  surrogate_scale: 14.907884894416696
  delta: 0.6387926357773329
  h_with_noise: false
  omega_std: 0.5
  lambda_u_upper: 0.0
  lambda_u_lower: 0.0
  lr_scale_per_layer: false
model:
  name: conv_snn
  net_type: conv
  in_shape:
  - 1
  - 28
  - 28
  num_classes: 10
  beta: 0.829643541684063
  threshold: 0.6559945203362026
  out_integrator: true
  algorithm_name: decolle
dataset:
  name: mnist
  supported_net_types:
  - fc
  - rec
  - conv
  T: 10
  seed: 59
  pin_memory: false
  download: true
  data_root: null
  num_workers: 4
  direct_coding: false
runtime:
  epochs: 20
  device: cuda
  seed: 42
  log_level: INFO
  neurobench: false
  batch_size: 256
  progress: true
optuna: {}
